// This file is automatically generated by Prisma. DO NOT EDIT.
// Prisma: A Modern Database Toolkit
//
// Generated from schema.prisma
//
// Learn more about Prisma: https://pris.ly/d/prisma-client

import { PrismaClient } from '@prisma/client';

export const prisma = new PrismaClient();